language: php

# Build Matrix
php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
env:
  - SYMFONY_VERSION="3.2.*"
matrix:
  fast_finish: true
  include:
    # Test lowest level dependencies are correct
    - php: 5.5
      env: LOWEST=1

    # Old non-LTS I still want to support
    - php: 5.5
      env: SYMFONY_VERSION="3.1.*" # 01/2017

    # Development versions
    - php: 5.5
      env: SYMFONY_VERSION="3.3.*@dev" # 05/2017 - 01/2018
    - php: 7.1
      env: SYMFONY_VERSION="3.3.*@dev"

  allow_failures:
    - env: SYMFONY_VERSION="3.3.*@dev"

cache:
  directories:
    - $HOME/.composer/cache

# Set up the project for testing
before_install:
  - echo "memory_limit=2560M" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - mkdir -p build/logs
install:
  # Install lowest stable dependencies
  - if [[ "$LOWEST" = "1" ]]; then composer update -n --prefer-dist --prefer-lowest --prefer-stable; fi
  # Install a particular Symfony version
  - if [[ ! -z "$SYMFONY_VERSION" ]]; then composer require symfony/symfony:${SYMFONY_VERSION} -n --prefer-dist; fi

# Run Tests
script:
  - php ./vendor/bin/phpunit --coverage-clover=build/logs/clover.xml

# Process results
after_script:
  # Send code coverage to scrutinizer-ci.com & coveralls.io
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml
  - wget https://github.com/satooshi/php-coveralls/releases/download/v1.0.0/coveralls.phar
  - travis_retry php coveralls.phar

notifications:
  email:
    - dev@dankempster.co.uk

branches:
  only:
    - develop
    - master
    - 1.0
