language: php
php:
  - 5.4
env:
  - SYMFONY_VERSION="2.3.*"
  - SYMFONY_VERSION="2.6.*"
  # - SYMFONY_VERSION="3.0.*@dev"
before_script:
  # - export COMPOSER_PATH=$(which composer)
  # - echo ${COMPOSER_PATH}
  # - php -d zend.gc_enabled=0 ${COMPOSER_PATH} -- require symfony/console:${SYMFONY_VERSION} symfony/framework-bundle:${SYMFONY_VERSION} --prefer-dist
  - composer require symfony/symfony:${SYMFONY_VERSION} --prefer-dist
script:
  # - phpunit -c phpunit.dist.xml
  - php ./vendor/bin/phpunit --coverage-clover=build/logs/clover.xml
after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml
  - php ./vendor/bin/coveralls -v
matrix:
  # Build with PHP 5.5 and Symfony LTS
  include:
    - php: 5.5
      env: SYMFONY_VERSION="2.3.*"
    - php: 5.6
      env: SYMFONY_VERSION="2.7.*@dev"

  # Test the latest PHP and Symfony Next
  allow_failures:
    - env: SYMFONY_VERSION="2.7.*@dev"

  fast_finish: true

notifications:
  email:
    - dev@dankempster.co.uk

branches:
  only:
    - develop
    - master
